### ISSUE TITLE
Error en el customer ID 

### ISSUE THREAD

**Issue by ensamblador** [aws-samples/multi-channel-customer-engagement#10]
Hi the Lambda function that saves the transcription to s3 **SaveTranscriptionToS3** is using 

        interaction = {
            'customerId': '1023456789',
            'interactionId': event["jobName"],
            'interactionDateTime': datetime.now().isoformat(),
            'interactionType': 'Call Transcript',
            'transcribeJobId': event["jobName"],
            'transcript': transcript_obj["results"]["transcripts"][0]["transcript"]
        }

And the function that extract comprehend NLP features uses 'customerId': '123456789', (whithout 0)

fixed by changing   'customerId': '1023456789' =>   'customerId': '123456789' on  **SaveTranscriptionToS3** function

**Comment by andres-lindo** [comment]
Resolved
