### ISSUE TITLE
AWSServiceRoleForLexBots not found

### ISSUE THREAD

**Issue by ensamblador** [aws-samples/multi-channel-customer-engagement#11]
If the account does not have an AWSServiceRoleForLexBots created, the bot fails when trying to get the sentiments of the client's utterances. It is solved by creating the role as indicated here https://docs.aws.amazon.com/lex/latest/dg/gs-create-role.html

**Comment by laumcaicedo** [comment]
Thanks, added to the prerequisites section :)

**Comment by andres-lindo** [comment]
AWSServiceRoleForLexBots creation included within the deployment script.
