### ISSUE TITLE
incorrect clarificationPrompt message

### ISSUE THREAD

**Issue by binli0114** [aws-samples/multi-channel-customer-engagement#12]
### Issue

The `clarificationPrompt message` shows non English
https://github.com/aws-samples/multi-channel-customer-engagement/blob/main/assets/bot-definition/amazon-lex/bot-en-us.json
```
"clarificationPrompt": {
        "maxAttempts": 5,
        "messages": [
            {
                "content": "Disculpa, no te entiendo. Puedes repetirlo?",
                "contentType": "PlainText"
            }
        ]
    }
```

### Solution

The message can ben changed to 
`Sorry I do not understand. Can you please repeat it?`

**Comment by jcristan** [comment]
Solved
