### ISSUE TITLE
The intent name 'welcomeMessage' is already in use with different casing

### ISSUE THREAD

**Issue by jcnovoa** [aws-samples/multi-channel-customer-engagement#14]
Perhaps the intents (or any resource that ought to be unique) might need to be aliased and added as part of the CFT parameters.
+ aws lex-models get-import --import-id 9aa4a9e6-92a0-41b7-a752-296bab1c9b61
--
980 | {
981 | "name": "multichannel_lex_bot",
982 | "resourceType": "BOT",
983 | "mergeStrategy": "OVERWRITE_LATEST",
984 | "importId": "9aa4a9e6-92a0-41b7-a752-296bab1c9b61",
985 | "importStatus": "FAILED",
986 | "failureReason": [
987 | "Intent names are case sensitive. The intent name 'welcomeMessage' is already in use with different casing. Check the intent name and try again."
988 | ],
989 | "createdDate": 1614120749.643
990 | }
991 | ++ aws lex-models get-import --import-id 9aa4a9e6-92a0-41b7-a752-296bab1c9b61 --output text --query importStatus
992 | + state=FAILED
993 | + test FAILED = COMPLETE

**Comment by andres-lindo** [comment]
Resolved.

Intent renamed to: welcomeMultichannel
